PizzaExample/PizzaClient/Models/Ingredient.cs
namespace PizzaClient.Models
{
    public class Ingredient
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

PizzaExample/PizzaClient/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using PizzaClient.Models;
using PizzaClient.Repository;

namespace PizzaClient.Controllers
{
    public class IngredientController : Controller
    {
        private const string GETALLINGREDIENTS = "GetAllIngredients";

        public List<Ingredient> GetAll()
        {
            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.GetResponse("api/ingredient/getIngredients");
            response.EnsureSuccessStatusCode();
            JArray ingredients = JArray.Parse(response.Content.ReadAsStringAsync().Result);

            List<Ingredient> ingredientsModel = new List<Ingredient>();
            foreach (JObject ingredient in ingredients)
            {
                Ingredient result = new Ingredient();
                result.Id = ingredient["Id"].Value<int>();
                result.Name = ingredient["Name"].Value<string>();

                ingredientsModel.Add(result);

            }

          
            return ingredientsModel;
        }

        public ActionResult GetAllIngredients()
        {
            try
            {
                
                ViewBag.Title = "All Ingredients";
                return View(GetAll());
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]  
        public ActionResult EditIngredient(int id)
        {
            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.GetResponse("api/ingredient/GetIngredient/" + id.ToString());
            response.EnsureSuccessStatusCode();
            JObject ingredient = JObject.Parse(response.Content.ReadAsStringAsync().Result);

            Ingredient result = new Ingredient();
            result.Id = ingredient["Id"].Value<int>();
            result.Name = ingredient["Name"].Value<string>();

            ViewBag.Title = "Edit Ingredient";
            return View(result);
        }

        [HttpPost]  
        public ActionResult Update(Ingredient ingredient)
        {
            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.PutResponse("api/ingredient/UpdateIngredient", ingredient);
            response.EnsureSuccessStatusCode();
            return RedirectToAction(GETALLINGREDIENTS);
        }

        public ActionResult Details(int id)
        {
            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.GetResponse("api/ingredient/getIngredient/" + id);
            response.EnsureSuccessStatusCode();
            JObject ingredient = JObject.Parse(response.Content.ReadAsStringAsync().Result);

            Ingredient result = new Ingredient();
            result.Id = ingredient["Id"].Value<int>();
            result.Name = ingredient["Name"].Value<string>();

            ViewBag.Title = "Ingredient Details";
            return View(result);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Ingredient ingredient)
        {
            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.PostResponse("api/ingredient/addIngredient", ingredient);
            response.EnsureSuccessStatusCode();
            return RedirectToAction(GETALLINGREDIENTS);
        }

        public ActionResult Delete(int id)
        {
            ServiceRepository serviceObj = new ServiceRepository();
            HttpResponseMessage response = serviceObj.DeleteResponse("api/ingredient/DeleteIngredient?id=" + id.ToString());
            response.EnsureSuccessStatusCode();
            return RedirectToAction(GETALLINGREDIENTS);
        }
    }
}

PizzaExample/PizzaClient/Views/Ingredient/Create.cshtml
@model PizzaClient.Models.Ingredient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ingredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAllIngredients")
</div>

PizzaExample/PizzaClient/Views/Ingredient/Details.cshtml
@model PizzaClient.Models.Ingredient

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>Ingredient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditIngredient", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "GetAllIngredients")
</p>  

PizzaExample/PizzaClient/Views/Ingredient/EditIngredient.cshtml
@model PizzaClient.Models.Ingredient

@{
    ViewBag.Title = "EditIngredient";
}

<h2>Edit Ingredient</h2>


@using (Html.BeginForm("Update", "Ingredient", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ingredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetAllIngredients")
</div>

PizzaExample/PizzaClient/Views/Ingredient/GetAllIngredients.cshtml
@model IEnumerable<PizzaClient.Models.Ingredient>

@{
    ViewBag.Title = "GetAllIngredients";
}

<h2>GetAllIngredients</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td>
                @Html.ActionLink("Edit", "EditIngredient", new { id = item.Id, name = item.Name, ingredient = item }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>